In [1]:
from __future__ import print_function
import torch
import numpy as np

# PyTorch

In [8]:
print(torch.__version__)

x = torch.rand(5, 3)
for i in range(len(x)):
    print ("Tensor: ", i, ", Size: " , len(x[i]), " elements with values: ",  x[i])

1.1.0a0+b457266
Tensor:  0 , Size:  3  elements with values:  tensor([0.4393, 0.6856, 0.2069])
Tensor:  1 , Size:  3  elements with values:  tensor([0.8861, 0.1582, 0.5716])
Tensor:  2 , Size:  3  elements with values:  tensor([0.0246, 0.2220, 0.9749])
Tensor:  3 , Size:  3  elements with values:  tensor([0.3394, 0.6250, 0.9662])
Tensor:  4 , Size:  3  elements with values:  tensor([0.1441, 0.6867, 0.1200])


# Numpy Tensors Representation

![title](../res/img/tensor.jpeg)

In [5]:
# Numpy Presentation of Tensors
scalar  = np.array(42)

print(scalar)
print('A scalar is of rank %d' %(scalar.ndim))
print('################################################')
vecor = np.array([1, 1, 2, 3, 5, 8])
print(vecor)
print('A vecor is of rank %d' %(vecor.ndim))
print('################################################')

matrix  = np.array([[1, 4, 7],
              [2, 5, 8],
              [3, 6, 9]])
print(matrix )
print('A matrix is of rank %d' %(matrix.ndim))
print('################################################')

tensor = np.array([[[1, 4, 7],
               [2, 5, 8],
               [3, 6, 9]],
              [[10, 40, 70],
               [20, 50, 80],
               [30, 60, 90]],
              [[100, 400, 700],
               [200, 500, 800],
               [300, 600, 900]]])
print(tensor)
print('This tensor is of rank %d' %(tensor.ndim))
print('################################################')

42
A scalar is of rank 0
################################################
[1 1 2 3 5 8]
A vecor is of rank 1
################################################
[[1 4 7]
 [2 5 8]
 [3 6 9]]
A matrix is of rank 2
################################################
[[[  1   4   7]
  [  2   5   8]
  [  3   6   9]]

 [[ 10  40  70]
  [ 20  50  80]
  [ 30  60  90]]

 [[100 400 700]
  [200 500 800]
  [300 600 900]]]
This tensor is of rank 3
################################################
